{"name": "test_add_to_favourite", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '[data-testid=\"nextMethodButton\"]')).click\n\nReason: NoSuchElementException: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[data-testid=\"nextMethodButton\"]\"}\n  (Session info: chrome=128.0.6613.137); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nScreenshot: file:///Users/maxnovo/.selene/screenshots/1743413805870/1743413805872.png\nPageSource: file:///Users/maxnovo/.selene/screenshots/1743413805870/1743413805872.html", "trace": "fn = <selene.core.wait.Command object at 0x104e0d880>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n>               return fn(self.entity)\n\n.venv/lib/python3.12/site-packages/selene/core/wait.py:119: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n.venv/lib/python3.12/site-packages/selene/core/wait.py:61: in __call__\n    return self._fn(entity)\n.venv/lib/python3.12/site-packages/selene/core/entity.py:525: in raw_click\n    element.locate().click()\n.venv/lib/python3.12/site-packages/selene/core/entity.py:185: in locate\n    return self._locator()\n.venv/lib/python3.12/site-packages/selene/core/locator.py:34: in __call__\n    return self._locate()\n.venv/lib/python3.12/site-packages/selene/core/_browser.py:71: in <lambda>\n    Locator(f'{self}.element({by})', lambda: self.driver.find_element(*by)),\n.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:898: in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n.venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:429: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x102df3d40>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"no such element\",\"message\":\"no such element: Unable to locate element: {\\...\\\\n#16 0x55fc28ed7013 \\\\u003Cunknown>\\\\n#17 0x55fc28ee6ebc \\\\u003Cunknown>\\\\n#18 0x7fe77fa51ac3 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[data-testid=\"nextMethodButton\"]\"}\nE         (Session info: chrome=128.0.6613.137); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE       Stacktrace:\nE       #0 0x55fc28ee80ca <unknown>\nE       #1 0x55fc28bb42b0 <unknown>\nE       #2 0x55fc28c03b22 <unknown>\nE       #3 0x55fc28c03dc1 <unknown>\nE       #4 0x55fc28c49994 <unknown>\nE       #5 0x55fc28c2892d <unknown>\nE       #6 0x55fc28c46e26 <unknown>\nE       #7 0x55fc28c286a3 <unknown>\nE       #8 0x55fc28bf64f3 <unknown>\nE       #9 0x55fc28bf74fe <unknown>\nE       #10 0x55fc28eaed7b <unknown>\nE       #11 0x55fc28eb2d31 <unknown>\nE       #12 0x55fc28e9ac85 <unknown>\nE       #13 0x55fc28eb38a2 <unknown>\nE       #14 0x55fc28e7fe1f <unknown>\nE       #15 0x55fc28ed6e48 <unknown>\nE       #16 0x55fc28ed7013 <unknown>\nE       #17 0x55fc28ee6ebc <unknown>\nE       #18 0x7fe77fa51ac3 <unknown>\n\n.venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: NoSuchElementException\n\nDuring handling of the above exception, another exception occurred:\n\n    @allure.tag(\"web\")\n    @allure.label(\"owner\", \"Max Razzhivin\")\n    @allure.feature(\"Проверяем добавление в избранное\")\n    @allure.story(\"Мы можем найти фильм и добавить в избранное\")\n    @allure.link(\"https://www.ivi.ru/\", \"Ivi.ru\")\n    @allure.severity(Severity.NORMAL)\n    def test_add_to_favourite():\n        main_page = Authorised()\n        find_page=NotAuthorised()\n        with allure.step(\"Открываем главную страницу\"):\n            open_page()\n    \n        with allure.step(\"Авторизуемся как существующий пользователь через логин и пароль\"):\n>           main_page.authorisation(email, password)\n\ntests/test_selene_ivi.py:96: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages/main_page.py:41: in authorisation\n    browser.element('[data-testid=\"nextMethodButton\"]').click()\n.venv/lib/python3.12/site-packages/selene/core/entity.py:540: in click\n    self.wait.for_(\n.venv/lib/python3.12/site-packages/selene/core/wait.py:150: in for_\n    return self._decorator(self)(logic)(fn)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfn = <selene.core.wait.Command object at 0x104e0d880>\n\n    def logic(fn: Callable[[E], R]) -> R:\n        finish_time = time.time() + self._timeout\n    \n        while True:\n            try:\n                return fn(self.entity)\n            except Exception as reason:\n                if time.time() > finish_time:\n                    reason_string = '{name}: {message}'.format(\n                        name=reason.__class__.__name__,\n                        message=getattr(reason, \"msg\", str(reason)),\n                    )\n                    # TODO: think on how can we improve logging failures in selene, e.g. reverse msg and stacktrace\n                    # stacktrace = getattr(reason, 'stacktrace', None)\n                    # TODO: should we have an option to turn on stacktrace logging?\n                    timeout = self._timeout\n                    entity = self.entity\n    \n                    # if it's a normal function, it should have __qualname__,\n                    # then use it, otherwise use str(fn)\n                    fn_name = getattr(\n                        fn,\n                        '__qualname__',\n                        getattr(fn, '__str__', lambda: str(fn))(),\n                    )\n    \n                    failure = TimeoutException(\n                        f'\\n'\n                        f'\\nTimed out after {timeout}s, while waiting for:'\n                        f'\\n{entity}.{fn_name}'\n                        f'\\n'\n                        f'\\nReason: {reason_string}'\n                    )\n    \n>                   raise self._hook_failure(failure)\nE                   selene.core.exceptions.TimeoutException: Message: \nE                   \nE                   Timed out after 4s, while waiting for:\nE                   browser.element(('css selector', '[data-testid=\"nextMethodButton\"]')).click\nE                   \nE                   Reason: NoSuchElementException: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[data-testid=\"nextMethodButton\"]\"}\nE                     (Session info: chrome=128.0.6613.137); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nE                   Screenshot: file:///Users/maxnovo/.selene/screenshots/1743413805870/1743413805872.png\nE                   PageSource: file:///Users/maxnovo/.selene/screenshots/1743413805870/1743413805872.html\n\n.venv/lib/python3.12/site-packages/selene/core/wait.py:148: TimeoutException"}, "steps": [{"name": "Открываем главную страницу", "status": "passed", "start": 1743413941980, "stop": 1743413948666}, {"name": "Авторизуемся как существующий пользователь через логин и пароль", "status": "failed", "statusDetails": {"message": "selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '[data-testid=\"nextMethodButton\"]')).click\n\nReason: NoSuchElementException: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[data-testid=\"nextMethodButton\"]\"}\n  (Session info: chrome=128.0.6613.137); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nScreenshot: file:///Users/maxnovo/.selene/screenshots/1743413805870/1743413805872.png\nPageSource: file:///Users/maxnovo/.selene/screenshots/1743413805870/1743413805872.html\n\n", "trace": "  File \"/Users/maxnovo/Desktop/qa.guru/Test_Project_Ivi/tests/test_selene_ivi.py\", line 96, in test_add_to_favourite\n    main_page.authorisation(email, password)\n  File \"/Users/maxnovo/Desktop/qa.guru/Test_Project_Ivi/pages/main_page.py\", line 41, in authorisation\n    browser.element('[data-testid=\"nextMethodButton\"]').click()\n  File \"/Users/maxnovo/Desktop/qa.guru/Test_Project_Ivi/.venv/lib/python3.12/site-packages/selene/core/entity.py\", line 540, in click\n    self.wait.for_(\n  File \"/Users/maxnovo/Desktop/qa.guru/Test_Project_Ivi/.venv/lib/python3.12/site-packages/selene/core/wait.py\", line 150, in for_\n    return self._decorator(self)(logic)(fn)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/maxnovo/Desktop/qa.guru/Test_Project_Ivi/.venv/lib/python3.12/site-packages/selene/core/wait.py\", line 148, in logic\n    raise self._hook_failure(failure)\n"}, "start": 1743413948667, "stop": 1743413958086}], "start": 1743413941980, "stop": 1743413958089, "uuid": "a443c609-4b92-444f-b868-5637960b1b05", "historyId": "9724fb054b85a375f62bc173edf44481", "testCaseId": "9724fb054b85a375f62bc173edf44481", "fullName": "tests.test_selene_ivi#test_add_to_favourite", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "web"}, {"name": "owner", "value": "Max Razzhivin"}, {"name": "feature", "value": "Проверяем добавление в избранное"}, {"name": "story", "value": "Мы можем найти фильм и добавить в избранное"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_selene_ivi"}, {"name": "host", "value": "MacBook-Air-MaxNovo.local"}, {"name": "thread", "value": "5705-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_selene_ivi"}], "links": [{"type": "Ivi.ru", "url": "https://www.ivi.ru/", "name": "https://www.ivi.ru/"}]}